apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsdok8st7-deployment
  labels:
    app: letsdok8st7
  namespace: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: letsdok8s-t7app
  template:
    metadata:
      labels:
        app: letsdok8s-t7app
    spec:
      containers:
      - name: letsdok8s-t7app
        image: 
        ports:
        - containerPort: 8080
      - name: letsdok8st7-db
        image: 
        ports:
        - containerPort: 80
